#!/usr/bin/expect

set timeout 20

puts "\n------ Valid Password Tests ------"
spawn ./deploy-dev-ops.sh -dt vmss -u a -dp aaa -l westus -ai appid -ak appkey
expect {
  "Enter a password" { puts "\nFailed: Can pass parameters before password"; send "aaaaaaaaaaaa\n" }
  timeout { exit -1 }
}
expect {
  "Confirm your password" { send "aaaaaaaaaaaa\n" }
  timeout { puts "\nFailed: Password is valid"; exit -1 }
}
expect {
  "Starting deployment..." { send \003 }
  timeout { puts "\nFailed: Password confirmation matches"; exit -1 }
}

puts "\n------ Invalid Password Tests ------"
spawn ./deploy-dev-ops.sh -dt vmss -u a -dp aaa -l westus -ai appid -ak appkey
expect {
  "Enter a password" { send "\n" }
  timeout { exit -1 }
}
expect {
  "Enter a password" { send "aaaaaaaaaaa\n" }
  timeout { puts "\nFailed: Password cannot be empty"; exit -1 }
}
expect {
  "Enter a password" { send "aaaaaaaaaaaa\n" }
  timeout { puts "\nFailed: Password cannot be too short"; exit -1 }
}
expect {
  "Confirm your password" { send "thispassworddoesnotmatch\n" }
  timeout { exit -1 }
}
expect {
  "Enter a password" { send \003 }
  timeout { puts "\nFailed: Confirming password must match"; exit -1 }
}

puts "\n"
spawn ./deploy-dev-ops.sh -dt vmss -u a -dp aaa -l westus -ai appid -ak appkey -p aaa -q
expect {
  "Error: The password" {}
  timeout { puts "\nFailed: Script did not throw error for bad password"; exit -1 }
}
expect {
  timeout { puts "\nFailed: Script did not immediately exit with bad parameter in quiet mode"; exit -1 }
  eof
}
