#!/usr/bin/expect

set fork [lindex $argv 0];
set branch [lindex $argv 1];

set timeout 20
spawn "./deploy-interactive.sh" -f "$fork" -b "$branch"

expect {
  "Do you want Spinnaker to target" { send "k8s\n" }
  timeout { exit -1 }
}

expect {
  "Enter a username" { send "a\n" }
  timeout { exit -1 }
}

###### Invalid ######
# Too short
expect {
  "Enter a dns prefix" { send "aa\n" }
  timeout { exit -1 }
}
# Too long
expect {
  "Enter a dns prefix" { send "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n" }
  timeout { exit -1 }
}
# Must start with a letter
expect {
  "Enter a dns prefix" { send "9aa\n" }
  timeout { exit -1 }
}
# No uppercase letters
expect {
  "Enter a dns prefix" { send "aaA\n" }
  timeout { exit -1 }
}
# No symbols other than hyphen
expect {
  "Enter a dns prefix" { send "aa?\n" }
  timeout { exit -1 }
}
expect {
  "Enter a dns prefix" { send "aa_\n" }
  timeout { exit -1 }
}
# Must end in letter or number
expect {
  "Enter a dns prefix" { send "aa-\n" }
  timeout { exit -1 }
}

###### Valid ######
# Can contain hyphens, can be three characters, can end in a number
expect {
  "Enter a dns prefix" { send "a-9\n" }
  timeout { exit -1 }
}

expect {
  "Enter the number corresponding to the location" { send \003\n }
  timeout { exit -1 }
}

interact

